"""Add soft delete and audit fields

Revision ID: 6f1c9cd71bb9
Revises: c3e991d2aa01
Create Date: 2026-09-28 21:55:55.583309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f1c9cd71bb9'
down_revision = 'c3e991d2aa01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity_created', ['entity', 'entity_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('assignment_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_history_complaint_id'), ['complaint_id'], unique=False)

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_complaints_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('department',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('skills',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('specialization')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('skills',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_complaints_deleted_at'))
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('assignment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_history_complaint_id'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_entity_created')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
