"""Secure attachments with paths thumbnails and soft delete

Revision ID: b448408ac878
Revises: d8d8f890b646
Create Date: 2026-09-28 17:56:50.799234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b448408ac878'
down_revision = 'd8d8f890b646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_path', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(length=500), nullable=True))

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('reported_department', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('equipment_serial_number', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('symptoms', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('operational_impact', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_complaints_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_reported_department'), ['reported_department'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_reported_department'))
        batch_op.drop_index(batch_op.f('ix_complaints_deleted_at'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('operational_impact')
        batch_op.drop_column('symptoms')
        batch_op.drop_column('equipment_serial_number')
        batch_op.drop_column('reported_department')
        batch_op.drop_column('location')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_path')
        batch_op.drop_column('storage_path')

    # ### end Alembic commands ###
