"""Add complaint tracking comments SLA and ETA

Revision ID: bb94878def10
Revises: b448408ac878
Create Date: 2026-09-28 18:06:00.978519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb94878def10'
down_revision = 'b448408ac878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_comments_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_comments_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('eta_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sla_due_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_complaints_sla_due_at'), ['sla_due_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_sla_due_at'))
        batch_op.drop_column('sla_due_at')
        batch_op.drop_column('eta_at')
        batch_op.drop_column('admin_notes')

    with op.batch_alter_table('complaint_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_complaint_comments_complaint_id'))

    op.drop_table('complaint_comments')
    # ### end Alembic commands ###
